[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["echo 'No build step required for server'"]

[start]
cmd = "cd server && node server.js"
